[package]
name = "code_analyze"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
regex = "1.10"
walkdir = "2.4"
colored = "2.1"
serde_json = "1.0.145"
serde = "1.0.228"

